### ISSUE TITLE
Add macOS ARM64 wheel support for PyPI with code signing

### ISSUE THREAD

**Issue by xerial** [wvlet/wvlet#1014]
## Summary

Add support for macOS ARM64 (Apple Silicon) wheels in the Python SDK PyPI distribution with proper code signing to meet macOS security requirements.

## Current State

- Python SDK already has code to support macOS ARM64 (`darwin_arm64/libwvlet.dylib`)
- Currently only building and publishing Linux wheels (manylinux2014)
- No macOS wheels are published to PyPI
- Native library needs code signing to avoid macOS Gatekeeper warnings

### 1. Code Signing
- `libwvlet.dylib` must be code signed to prevent macOS security warnings
- Ad-hoc signing (`codesign --sign -`) is sufficient for PyPI distribution
- No need for Developer ID certificate for open source distribution

### 2. Platform Support
- Only support macOS ARM64 (Apple Silicon)
- No Intel Mac support needed (deprecated)

### 3. Wheel Building
- Build native macOS ARM64 wheels on GitHub Actions macOS runners
- Use `delocate` to create proper relocatable wheels
- Ensure signed libraries are bundled correctly

### Phase 1: Native Library Signing
- [ ] Update `wvc-lib` build process to sign `libwvlet.dylib` on macOS
- [ ] Add `codesign --sign - --force` step after library build
- [ ] Verify signature with `codesign --verify`

### Phase 2: GitHub Actions Workflow
- [ ] Add macOS runner to build matrix
- [ ] Download or build native library for macOS ARM64
- [ ] Ensure library is properly signed in the workflow
- [ ] Build macOS-specific wheel with proper platform tags

### Phase 3: Wheel Building
- [ ] Install and use `delocate` for macOS wheels
- [ ] Ensure wheel contains signed dylib
- [ ] Proper wheel naming: `wvlet-{version}-py3-none-macosx_11_0_arm64.whl`

### Phase 4: Testing
- [ ] Test wheel installation on macOS ARM64
- [ ] Verify no security warnings when loading library
- [ ] Add automated test for library loading

## Example Workflow Changes

```yaml
build-wheels:
  strategy:
    matrix:
      include:
        - os: macos-latest
          platform: macos
          arch: arm64
  steps:
    - name: Build and sign native library
      if: matrix.platform == 'macos'
      run: |
        # Build native library
        cd wvc-lib
        make
        # Sign the library
        codesign --sign - --force target/scala-*/libwvlet.dylib
        # Verify
        codesign --verify --verbose target/scala-*/libwvlet.dylib
```

## Benefits

- macOS users can install via `pip install wvlet` without building from source
- No security warnings or Gatekeeper issues
- Native performance on Apple Silicon Macs
- Improved developer experience

## Testing

Manual testing checklist:
- [ ] `pip install wvlet` works on macOS ARM64
- [ ] No security dialogs when importing the module
- [ ] `from wvlet import compile` loads successfully
- [ ] Compilation works with native library

## References

- [Apple Code Signing Guide](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html)
- [delocate documentation](https://github.com/matthew-brett/delocate)
- [cibuildwheel for cross-platform wheels](https://cibuildwheel.readthedocs.io/)
